user nginx;

events{
  worker_connections 1024;
}

http{
  resolver 127.0.0.11 valid=30s; # Docker default DNS discovery server

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }
  upstream websocket{
    # Contacts directly the Docker's DNS for replica set named pythonserve and will use Docker DNS Round Robin
    server pythonserver:5002;
  }
  server{
    listen 5002;
    location / {
      proxy_pass http://websocket;
      proxy_next_upstream error;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }
  }
}